### ISSUE TITLE
disableNameSuffixHash: true is not working

### ISSUE THREAD

**Issue by mabushey** [goabout/kustomize-sopssecretgenerator#17]
Thanks again for such an awesome tool!
I installed version 1.3.2:
```
✗  ls -l ~/.config/kustomize/plugin/goabout.com/v1beta1/sopssecretgenerator/SopsSecretGenerator
-rwxr-xr-- 1 ubuntu ubuntu 21028864 Sep 15 09:17 /home/ubuntu/.config/kustomize/plugin/goabout.com/v1beta1/sopssecretgenerator/SopsSecretGenerator
```

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
generators:
- sops_sshkey_generator.yaml
```

sops_sshkey_generator.yaml:
```
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: creds
  annotations:
    managed-by: argocd.argoproj.io
  disableNameSuffixHash: true
files:
  - sshPrivateKey=secrets/id_ed25519_github-argocd.enc
```

✗  kustomize build --enable_alpha_plugins .
```
apiVersion: v1
data:
  sshPrivateKey: [Redacted]
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  name: creds-5d7tdtb2m7
  namespace: argocd
```

The hash is still there...
