### ISSUE TITLE
hash extensions not working the same w/plugin

### ISSUE THREAD

**Issue by mabushey** [goabout/kustomize-sopssecretgenerator#19]
This plugin is great, thank you. :) I'm switching over an existing project to use this plugin.

This works, using an env file:
```
✗  cat dev-cdx/auth_generator.yaml 
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: auth
envs:
  - secrets/auth.enc.env
```

The code in the deployment is (no changes):
```
        env:
        - name: AUTH_ISSUER
          valueFrom:
            secretKeyRef:
              name: auth
              key: issuer-hostname
```

Building and applying the diff [in the deployment] is:
```
-              name: auth-mht6tm85m2
+              name: auth-cf2kbg8c7t
```

I applied the new secrret (auth-cf2kbg8c7t)  and compared the contents of the two secrets, they are exactly the same. The hash must include more than just the data. I would prefer if the data is the same for it to be the same hash, but this is probably a kustomize thing. I can live with this, it's just not ideal.
 
This is NOT working right, using a plain file:
```
✗  cat dev-cdx/encoding_generator.yaml 
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: encoding-key
files:
  - secrets/encoding-key.enc.yaml
```

It generated this:
```
apiVersion: v1
data:
  encoding-key.enc.yaml: ...[redacted]...==
kind: Secret
metadata:
  name: encoding-key-6985f5h8h2
  namespace: auth
```

We have a new hash, like the previous env example it's not the same hash as without the sops plugin.

The code in the deployment (no change):
```
      volumes:
      - name: data-vol
        projected:
          sources:
...
          - secret:
              name: auth-encoding-key
```

Building and applying the diff [in the deployment] is:
```
-              name: auth-encoding-key-57tkch25m4
+              name: auth-encoding-key
```

It's no longer referencing the hash (it did before the plugin), so it won't work (new correct value is `encoding-key-6985f5h8h2`).

I'm using ArgoCD, so it's import to have the hash so if a new value is committed it will be updated.
