### ISSUE TITLE
Is it possible to patch/add a data element to a secret that already exists?

### ISSUE THREAD

**Issue by mabushey** [goabout/kustomize-sopssecretgenerator#27]
First off this plugin is essential. It makes me sad you only have 69 stars; You should have thousands. Thank you for such a useful tool.

ArgoCD has a secret, `argocd-secret` that is already created. I need to add an element like
```
stringData:
  # github webhook secret
  webhook.github.secret: shhhh! it's a github secret
```
The problem is the secret name already exists. I can create it as `argocd-secret2` without errors, but using the name `argocd-secret`, I get:
```
Error: namespace transformation produces ID conflict: [{"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{"config.kubernetes.io/previousKinds":"Secret","config.kubernetes.io/previousNames":"argocd-secret","config.kubernetes.io/previousNamespaces":"default"},"labels":{"app.kubernetes.io/name":"argocd-secret","app.kubernetes.io/part-of":"argocd"},"name":"argocd-secret","namespace":"argocd"},"type":"Opaque"}{nsfx:false,beh:unspecified} {"apiVersion":"v1","data":{"webhook.github.secret":"[Redacted]"},"kind":"Secret","metadata":{"name":"argocd-secret","namespace":"argocd"}}{nsfx:false,beh:unspecified}]
```
Is there a way to use this to patch an existing secret? Thank you!

**Comment by jcassee** [comment]
Hi @mabushey, I think you should be able to use `behavior: merge`:
```
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: my-secret
behavior: merge
[...]
```

**Comment by mabushey** [comment]
Thanks for being so responsive!

Using the name argocd-secret2, I get this from kustomize:
```
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
---
apiVersion: v1
data:
  webhook.github.secret: RmI4aG5tZzRvUE1VZEg=
kind: Secret
metadata:
  name: argocd-secret2
  namespace: argocd
---
```
Using `argocd-secret` I get the error from the previous message. With `behavior: merge`, I get:
```
Error: merging from generator &{/home/ubuntu/.config/kustomize/plugin/goabout.com/v1beta1/sopssecretgenerator/SopsSecretGenerator [] [97 112 105 86 101 114 115 105 111 110 58 32 103 111 97 98 111 117 116 46 99 111 109 47 118 49 98 101 116 97 49 10 98 101 104 97 118 105 111 114 58 32 109 101 114 103 101 10 100 105 115 97 98 108 101 78 97 109 101 83 117 102 102 105 120 72 97 115 104 58 32 116 114 117 101 10 101 110 118 115 58 10 45 32 115 101 99 114 101 116 115 47 97 114 103 111 99 100 45 115 101 99 114 101 116 46 101 110 99 46 101 110 118 10 107 105 110 100 58 32 83 111 112 115 83 101 99 114 101 116 71 101 110 101 114 97 116 111 114 10 109 101 116 97 100 97 116 97 58 10 32 32 110 97 109 101 58 32 97 114 103 111 99 100 45 115 101 99 114 101 116 10 32 32 110 97 109 101 115 112 97 99 101 58 32 97 114 103 111 99 100 10] 0xc0027727b0}: id resid.ResId{Gvk:resid.Gvk{Group:"", Version:"v1", Kind:"Secret", isClusterScoped:false}, Name:"argocd-secret", Namespace:"argocd"} does not exist; cannot merge or replace
```

generator-argocd-secret.yaml:
```
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: argocd-secret
  namespace: argocd
behavior: merge
disableNameSuffixHash: true
envs:
  - secrets/argocd-secret.enc.env
```

**Comment by jcassee** [comment]
So the idea is that you first include the Secret named _argocd-secret_ under `resources:` in _kustomize.yaml_, and then use the same name in the SopsSecretGenerator. That should get the entries merged.

**Comment by mabushey** [comment]
Hi @jcassee :) Thanks for your time/effort.

I use a Makefile to download argocd:
```
        curl -LSs -o argocd-install.yaml https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.7/manifests/install.yaml
```
✗  cat argocd-install.yaml | grep -A2 -B7 " name: argocd-secret"
```
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
type: Opaque
---
```
Of course in kustomize.yaml under resources I list argocd-install.yaml. I think the problem is it's a secret with labels but NO data.
