### ISSUE TITLE
Kustomize KRM exec plugin generates no output

### ISSUE THREAD

**Issue by lack** [goabout/kustomize-sopssecretgenerator#36]
I am trying to set up SopsSecretGenerator via a kustomize krm plugin.

Here is the SopsSecretGenerator yaml:
```yaml
apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
  name: my-secret
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: SopsSecretGenerator
files:
  - ./rclone.conf
```

And the associated kustomization.yaml that generates no errors and no output:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - ./secrets.enc.yaml
```

I verified that the actual data (rclone.conf) is properly encrypted and `sops -d rclone.conf` renders the cleartext properly and running SopsSecretGenerator on it in legacy mode renders a well-formed Secret object with the right context.

Also, if I change the `files` section to refer to a nonexistant path, I get an error message so I know kustomize is calling the plugin.

**Comment by lack** [comment]
After some extensive debugging, I have the root cause figured out.

First I replaced direct invocation of SopsSecretGenerator with this bash script:

```bash
#!/bin/bash

tee in.yaml | \
    SopsSecretGenerator | \
    tee out.yaml
```

Here's what I saw in `in.yaml`
```yaml
apiVersion: config.kubernetes.io/v1
kind: ResourceList
items:
- apiVersion: goabout.com/v1beta1
  files:
  - ./rclone.conf
  kind: SopsSecretGenerator
  metadata:
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ./logger
      config.kubernetes.io/local-config: 'true'
      config.kubernetes.io/index: '0'
      internal.config.kubernetes.io/index: '0'
      internal.config.kubernetes.io/annotations-migration-resource-id: '0'
      internal.config.kubernetes.io/id: '1'
      config.k8s.io/id: '1'
    name: my-secret
functionConfig:
  apiVersion: goabout.com/v1beta1
  files:
  - ./rclone.conf
  kind: SopsSecretGenerator
  metadata:
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ./logger
      config.kubernetes.io/local-config: 'true'
    name: my-secret
```

And here's `out.yaml`
```yaml
apiVersion: config.kubernetes.io/v1
kind: ResourceList
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: my-secret-2
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ./logger
      config.kubernetes.io/local-config: 'true'
      config.k8s.io/id: "1"
      config.kubernetes.io/index: "0"
      internal.config.kubernetes.io/annotations-migration-resource-id: "0"
      internal.config.kubernetes.io/id: "1"
      internal.config.kubernetes.io/index: "0"
      kustomize.config.k8s.io/needs-hash: "true"
  data:
    rclone.conf: W2d... etc... correct decrypted base64 content
functionConfig:
  apiVersion: goabout.com/v1beta1
  files:
  - ./rclone.conf
  kind: SopsSecretGenerator
  metadata:
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: ./logger
      config.kubernetes.io/local-config: 'true'
    name: my-secret-2
```

At first it seemed perfect, and that kustomize was just broken. But after a session where I instrumented kustomize with a ton of logging, I found the issue:
```
config.kubernetes.io/local-config: 'true'
```

When this is in annotations of the output object, kustomize treats it as a local config object and removes it from the final rendered output.

So in order to generate content that kustomize will actually produce as output, a krm plugin such as SopsSecretGenerator needs to strip away this annotation.
